#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

#define SPAWN_PALLET_TOWN 1
#define SPAWN_VIRIDIAN_CITY 2
#define SPAWN_PEWTER_CITY 3
#define SPAWN_CERULEAN_CITY 4
#define SPAWN_LAVENDER_TOWN 5
#define SPAWN_VERMILION_CITY 6
#define SPAWN_CELADON_CITY 7
#define SPAWN_FUCHSIA_CITY 8
#define SPAWN_CINNABAR_ISLAND 9
#define SPAWN_INDIGO_PLATEAU 10
#define SPAWN_SAFFRON_CITY 11
#define SPAWN_ROUTE4 12
#define SPAWN_ROUTE10 13

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
