FuchsiaCity_House3_Text_WouldYouLikeToForgetMove:: @ 81993B9
    .string "Uh…\n"
    .string "Oh, yes, I'm the MOVE DELETER.\p"
    .string "I can make POKéMON forget their\n"
    .string "moves.\p"
    .string "Would you like me to do that?$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove:: @ 8199421
    .string "Which POKéMON should forget a\n"
    .string "move?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten:: @ 8199445
    .string "Which move should be forgotten?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove:: @ 8199465
    .string "{STR_VAR_1} seems to know only one\n"
    .string "move…$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten:: @ 8199485
    .string "Hm! {STR_VAR_1}'s {STR_VAR_2}?\n"
    .string "That move should be forgotten?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely:: @ 81994B1
    .string "It worked to perfection!\p"
    .string "{STR_VAR_1} has forgotten\n"
    .string "{STR_VAR_2} completely.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves:: @ 81994EA
    .string "Come again if there are other\n"
    .string "moves to be forgotten.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves:: @ 819951F
    .string "What?\n"
    .string "No EGG should know any moves.$"

FuchsiaCity_House3_Text_WantMeToTeachMove:: @ 81A2C63
    .string "I'm the POKéMON MOVE MANIAC.\p"
    .string "I know every single move that\n"
    .string "POKéMON learn growing up.\p"
    .string "Do you want me to teach a move\n"
    .string "to a POKéMON of yours?$"

FuchsiaCity_House3_Text_TutorWhichMon:: @ 81A2CC3
    .string "Which POKéMON needs tutoring?$"

FuchsiaCity_House3_Text_TeachWhichMove:: @ 81A2CE1
    .string "Which move should I teach?$"

FuchsiaCity_House3_Text_NoMoveICanTeachThatMon:: @ 81A2CFC
    .string "Sorry…\p"
    .string "It doesn't appear as if I have a\n"
    .string "move I can teach that POKéMON.$"

FuchsiaCity_House3_Text_CantTeachAnEgg:: @ 81A2E20
    .string "Hunh? There isn't a single move\n"
    .string "that I can teach an EGG.$"

FuchsiaCity_House3_Text_EndToLearnMove:: @ 81A2DE0
    .string "If your POKéMON need to learn a\n"
    .string "move, Let me know.$"
