FuchsiaCity_House3_Text_WouldYouLikeToForgetMove:: @ 81993B9
    .string "Uh…\n"
    .string "Oh, yes, I'm the MOVE DELETER.\p"
    .string "I can make POKéMON forget their\n"
    .string "moves.\p"
    .string "Would you like me to do that?$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove:: @ 8199421
    .string "Which POKéMON should forget a\n"
    .string "move?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten:: @ 8199445
    .string "Which move should be forgotten?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove:: @ 8199465
    .string "{STR_VAR_1} seems to know only one\n"
    .string "move…$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten:: @ 8199485
    .string "Hm! {STR_VAR_1}'s {STR_VAR_2}?\n"
    .string "That move should be forgotten?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely:: @ 81994B1
    .string "It worked to perfection!\p"
    .string "{STR_VAR_1} has forgotten\n"
    .string "{STR_VAR_2} completely.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves:: @ 81994EA
    .string "Come again if there are other\n"
    .string "moves to be forgotten.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves:: @ 819951F
    .string "What?\n"
    .string "No EGG should know any moves.$"

FuchsiaCity_House3_Text_WantMeToTeachMove:: @ 81A2C63
    .string "I'm the POKéMON MOVE MANIAC.\p"
    .string "I know every single move that\n"
    .string "POKéMON learn growing up.\p"
    .string "Do you want me to teach a move\n"
    .string "to a POKéMON of yours?$"

FuchsiaCity_House3_Text_TutorWhichMon:: @ 81A2CC3
    .string "Which POKéMON needs tutoring?$"

FuchsiaCity_House3_Text_TeachWhichMove:: @ 81A2CE1
    .string "Which move should I teach?$"

FuchsiaCity_House3_Text_NoMoveICanTeachThatMon:: @ 81A2CFC
    .string "Sorry…\p"
    .string "It doesn't appear as if I have a\n"
    .string "move I can teach that POKéMON.$"

FuchsiaCity_House3_Text_CantTeachAnEgg:: @ 81A2E20
    .string "Hunh? There isn't a single move\n"
    .string "that I can teach an EGG.$"

FuchsiaCity_House3_Text_EndToLearnMove:: @ 81A2DE0
    .string "If your POKéMON need to learn a\n"
    .string "move, Let me know.$"

Text_UltimateMoveThatMon:: @ 81A46C6
    .string "I perfected the ultimate move of\n"
    .string "its type…\p"
    .string "But will no one take it for\n"
    .string "future use?\p"
    .string "…Hm? Hmmm!\p"
    .string "Y-you…\n"
    .string "Th-that {STR_VAR_1}…$"

Text_JustMistaken:: @ 81A4737
    .string "…No…\n"
    .string "I was just mistaken.$"

Text_AllowMeToTeachMonUltimateMove:: @ 81A4751
    .string "Oh! This is the one!\n"
    .string "This is the POKéMON!\p"
    .string "This {STR_VAR_1} is worthy of\n"
    .string "learning my ultimate move!\p"
    .string "Will you allow it?\p"
    .string "Will you allow your {STR_VAR_1} to\n"
    .string "learn my {STR_VAR_2}?$"

Text_YouRejectIt:: @ 81A47E5
    .string "Gaah! You reject it?\n"
    .string "No, I won't be dissuaded!$"

Text_LetMeConferUltimateMove:: @ 81A4814
    .string "You will allow it?\p"
    .string "Then, let me confer my ultimate\n"
    .string "{STR_VAR_2} on your {STR_VAR_1}.\p"
    .string "Ggggrah-awooo!$"

Text_TaughtMove:: @ 81A4865
    .string "Gasp, gasp, gasp…\p"
    .string "I didn't think I could teach that\n"
    .string "move while I still lived…$"

Text_MakeBestUseOfMove:: @ 81A48B3
    .string "I implore you to make the best\n"
    .string "use of that move and gain power!$"

Text_PassedOnEverythingIKnow:: @ 81A48F3
    .string "Gasp, gasp, gasp…\p"
    .string "I have no regrets now.\n"
    .string "I've passed on everything I know.\p"
    .string "Now I can live out my life knowing\n"
    .string "my work is done.$"

Text_FeelRejuvenated:: @ 81A4972
    .string "After I passed on my knowledge to\n"
    .string "you, I felt so much relief.\p"
    .string "In fact, I feel rejuvenated,\n"
    .string "as if I were younger again!$"
